# -*- coding: utf8 -*-
'''
Created on 2014-11-05
@author: zen
'''

# 设备名称
DEVICES_NAME = 'DEVICES_NAME'
#设备android版本
DEVICES_AND_VERSION = 'DEVICES_AND_VERSION'
#设备SDK版本
DEVICES_SDK_VERSION = 'DEVICES_SDK_VERSION'
#设备CPU类型
DEVICES_CPU_TYPE = 'DEVICES_CPU_TYPE'
#设备HEAPSIZE
DEVICES_HEAPSIZE = 'DEVICES_HEAPSIZE'
#设备分辨率
DEVICES_DISP_SIZE = 'DEVICES_DISP_SIZE'