# -*- coding: utf8 -*-
'''
Created on 2014-10-17
@author: zen
'''
# #######################################################
#电话键
########################################################
KEYCODE_CALL = 5  #拨号键
KEYCODE_ENDCALL = 6  #挂机键	 6
KEYCODE_HOME = 3  #按键Home	 3
KEYCODE_MENU = 82  #菜单键	 82
KEYCODE_BACK = 4  #返回键	 4
KEYCODE_SEARCH = 84  #搜索键	 84
KEYCODE_CAMERA = 27  #拍照键	 27
KEYCODE_FOCUS = 80  #拍照对焦键	 80
KEYCODE_POWER = 26  #电源键	 26
KEYCODE_NOTIFICATION = 83  #通知键	 83
KEYCODE_MUTE = 91  #话筒静音键	 91
KEYCODE_VOLUME_MUTE = 164  #扬声器静音键	 164
KEYCODE_VOLUME_UP = 24  #音量增加键	 24
KEYCODE_VOLUME_DOWN = 25  #音量减小键	 25
KEYCODE_DPAD_UP = 19  #导航键 向上	 19
KEYCODE_DPAD_DOWN = 20  #导航键 向下	 20
KEYCODE_DPAD_LEFT = 21  #导航键 向左	 21
KEYCODE_DPAD_RIGHT = 22  #导航键 向右	 22
KEYCODE_DPAD_CENTER = 23  #导航键 确定键	 23
KEYCODE_PAGE_UP = 92  #向上翻页键	 92
KEYCODE_PAGE_DOWN = 93  #向下翻页键	 93
KEYCODE_FORWARD_DEL = 112  #删除键	 112
SYSKEYLIST = [KEYCODE_CALL, KEYCODE_ENDCALL, KEYCODE_HOME, KEYCODE_MENU, KEYCODE_BACK,
              KEYCODE_CAMERA, KEYCODE_VOLUME_UP, KEYCODE_VOLUME_DOWN,
              KEYCODE_DPAD_UP, KEYCODE_DPAD_DOWN, KEYCODE_DPAD_LEFT, KEYCODE_DPAD_RIGHT, KEYCODE_DPAD_CENTER,
              KEYCODE_PAGE_UP, KEYCODE_PAGE_DOWN, KEYCODE_FORWARD_DEL
]


########################################################
#基本
########################################################
KEYCODE_0 = 7  #按键'0'	 7
KEYCODE_1 = 8  #按键'1'	 8
KEYCODE_2 = 9  #按键'2'	 9
KEYCODE_3 = 10  #按键'3'	 10
KEYCODE_4 = 11  #按键'4'	 11
KEYCODE_5 = 12  #按键'5'	 12
KEYCODE_6 = 13  #按键'6'	 13
KEYCODE_7 = 14  #按键'7'	 14
KEYCODE_8 = 15  #按键'8'	 15
KEYCODE_9 = 16  #按键'9'	 16
KEYCODE_A = 29  #按键'A'	 29
KEYCODE_B = 30  #按键'B'	 30
KEYCODE_C = 31  #按键'C'	 31
KEYCODE_D = 32  #按键'D'	 32
KEYCODE_E = 33  #按键'E'	 33
KEYCODE_F = 34  #按键'F'	 34
KEYCODE_G = 35  #按键'G'	 35
KEYCODE_H = 36  #按键'H'	 36
KEYCODE_I = 37  #按键'I'	 37
KEYCODE_J = 38  #按键'J'	 38
KEYCODE_K = 39  #按键'K'	 39
KEYCODE_L = 40  #按键'L'	 40
KEYCODE_M = 41  #按键'M'	 41
KEYCODE_N = 42  #按键'N'	 42
KEYCODE_O = 43  #按键'O'	 43
KEYCODE_P = 44  #按键'P'	 44
KEYCODE_Q = 45  #按键'Q'	 45
KEYCODE_R = 46  #按键'R'	 46
KEYCODE_S = 47  #按键'S'	 47
KEYCODE_T = 48  #按键'T'	 48
KEYCODE_U = 49  #按键'U'	 49
KEYCODE_V = 50  #按键'V'	 50
KEYCODE_W = 51  #按键'W'	 51
KEYCODE_X = 52  #按键'X'	 52
KEYCODE_Y = 53  #按键'Y'	 53
KEYCODE_Z = 54  #按键'Z'	 54
NORKEYLIST = [
    KEYCODE_0, KEYCODE_1, KEYCODE_2, KEYCODE_3, KEYCODE_4, KEYCODE_5,
    KEYCODE_6, KEYCODE_7, KEYCODE_8, KEYCODE_9,
    KEYCODE_A, KEYCODE_B, KEYCODE_C, KEYCODE_D, KEYCODE_E, KEYCODE_F,
    KEYCODE_G, KEYCODE_H, KEYCODE_I, KEYCODE_J, KEYCODE_K, KEYCODE_L,
    KEYCODE_M, KEYCODE_N, KEYCODE_O, KEYCODE_P, KEYCODE_Q, KEYCODE_R,
    KEYCODE_S, KEYCODE_T, KEYCODE_U, KEYCODE_V, KEYCODE_W, KEYCODE_X,
    KEYCODE_Y, KEYCODE_Z
]