# -*- coding: utf8 -*-
'''
Created on 2014-10-17
@author: zen
'''

# 检测设备连接
EVT_CHECK_DEVICES = 'EVT_CHECK_DEVICES'
#选中被测程序安装
EVT_ENABLD_INSTALL_AUT = 'EVT_ENABLD_INSTALL_AUT'
#浏览被测程序
EVT_SCAN_AUT = 'EVT_SCAN_AUT'
#选择被测程序
EVT_SELECT_AUT = 'EVT_SELECT_AUT'
#选择操作间隔
EVT_SELECT_OPT_INTERVAL = 'EVT_SELECT_OPT_INTERVAL'

#开始运行monkey
EVT_START_MONKEY = 'EVT_START_RUN'
#开始运行monkey checker
EVT_START_MONKEY_CHECKER = 'EVT_START_MONKEY_CHECKER'
#停止运行
EVT_STOP_RUN = 'EVT_STOP_RUN'

#浏览日志存储位置
EVT_SCAN_LOG_PATH = 'EVT_SCAN_LOG_PATH'
#打开日志存储位置
EVT_OPEN_LOG_PATH = 'EVT_OPEN_LOG_PATH'
#清楚屏幕日志
EVT_CLEAR_SCREEN_LOG = 'EVT_CLEAR_SCREEN_LOG'